---
deployment:
  tasks:
    - export APPPATH=/home1/jrobak/dev.hippiehost.com
    - /bin/mkdir -p $APPPATH
    - /usr/bin/rsync -a --delete --exclude='.git' --exclude='node_modules' --exclude='vendor' --exclude='.env' --exclude='storage/app/public' ./ $APPPATH/
    - /bin/cd $APPPATH && /usr/bin/env composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader || true
    - /bin/cd $APPPATH && /usr/local/bin/php artisan optimize:clear || true
    - /bin/cd $APPPATH && /usr/local/bin/php artisan config:cache || true
    - /bin/cd $APPPATH && /usr/local/bin/php artisan route:cache || true
    - /bin/cd $APPPATH && /usr/local/bin/php artisan view:cache || true
